### ISSUE TITLE
初始化初始不了

### ISSUE THREAD

**Issue by CrazyCJay** [xiaolyuh/mrtf-git-flow-4idea#9]
点击初始配置，分支能创建，配置文件创建不了，无法使用

**Comment by CrazyCJay** [comment]
麻烦大神处理下，最新的idea工具下，另外在工具栏找不到，只能在状态栏找到插件

**Comment by CrazyCJay** [comment]
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON

**Comment by xiaolyuh123** [comment]
你master分支存在不


发自我的iPhone

**Comment by CrazyCJay** [comment]
存在的，初始化，在master分支基础下，test release都生产并上传了

**Comment by CrazyCJay** [comment]
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
	at com.github.xiaolyuh.action.InitPluginAction$1.run(InitPluginAction.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON PluginClassLoader[PluginDescriptor(name=GitFlowPlus, id=com.github.xiaolyuh.mrtf-git-flow-4idea, path=C:\Users\Administrator\AppData\Roaming\JetBrains\WebStorm2020.2\plugins\git-flow-plus-4idea-1.0.12.jar, version=1.0.12)] com.intellij.ide.plugins.cl.PluginClassLoader@5dcc3145
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more

**Comment by CrazyCJay** [comment]
感觉是缺少fastjson

**Comment by xiaolyuh123** [comment]
你装的那个版本


发自我的iPhone
